// <auto-generated />
using System;
using BeniceSoft.Abp.Sample.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace BeniceSoft.Abp.Sample.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeniceSoft.Abp.Sample.Domain.AMRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatorId")
                        .HasComment("创建人Id");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CreatorName")
                        .HasComment("创建人姓名");

                    b.Property<long?>("DeleterId")
                        .HasColumnType("bigint")
                        .HasColumnName("DeleterId")
                        .HasComment("删除人Id");

                    b.Property<string>("DeleterName")
                        .HasColumnType("text")
                        .HasColumnName("DeleterName")
                        .HasComment("删除人姓名");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletionTime")
                        .HasComment("删除时间");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties")
                        .HasComment("扩展属性");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted")
                        .HasComment("是否已删除");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最新修改时间");

                    b.Property<long?>("LastModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("LastModifierId")
                        .HasComment("最新修改人Id");

                    b.Property<string>("LastModifierName")
                        .HasColumnType("text")
                        .HasColumnName("LastModifierName")
                        .HasComment("最新修改人姓名");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("am_roles", (string)null);
                });

            modelBuilder.Entity("BeniceSoft.Abp.Sample.Domain.AMUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatorId")
                        .HasComment("创建人Id");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CreatorName")
                        .HasComment("创建人姓名");

                    b.Property<long?>("DeleterId")
                        .HasColumnType("bigint")
                        .HasColumnName("DeleterId")
                        .HasComment("删除人Id");

                    b.Property<string>("DeleterName")
                        .HasColumnType("text")
                        .HasColumnName("DeleterName")
                        .HasComment("删除人姓名");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletionTime")
                        .HasComment("删除时间");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties")
                        .HasComment("扩展属性");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted")
                        .HasComment("是否已删除");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最新修改时间");

                    b.Property<long?>("LastModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("LastModifierId")
                        .HasComment("最新修改人Id");

                    b.Property<string>("LastModifierName")
                        .HasColumnType("text")
                        .HasColumnName("LastModifierName")
                        .HasComment("最新修改人姓名");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("am_users", (string)null);
                });

            modelBuilder.Entity("BeniceSoft.Abp.Sample.Domain.AmUserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("用户id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasComment("角色id");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("am_userroles", (string)null);
                });

            modelBuilder.Entity("BeniceSoft.Abp.Sample.Domain.BulkDemoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BatchTag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchTag");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("bulk_demo_items", (string)null);
                });

            modelBuilder.Entity("BeniceSoft.Abp.Sample.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("BeniceSoft.Abp.Sample.Domain.SalesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("BatchTag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BatchTag");

                    b.HasIndex("OrderNo");

                    b.HasIndex("OrderTime");

                    b.HasIndex("ProductCode");

                    b.ToTable("sales_orders", (string)null);
                });

            modelBuilder.Entity("BeniceSoft.Abp.Sample.Domain.AmUserRole", b =>
                {
                    b.HasOne("BeniceSoft.Abp.Sample.Domain.AMUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeniceSoft.Abp.Sample.Domain.AMUser", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
