<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props" />

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Volo.Abp.Authorization" />
		<PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
		<PackageReference Include="Microsoft.IdentityModel.Abstractions" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
		<PackageReference Include="Microsoft.IdentityModel.Logging" />
		<PackageReference Include="Microsoft.IdentityModel.Protocols" />
		<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.Caching.StackExchangeRedis" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BeniceSoft.Abp.Auth.Core\BeniceSoft.Abp.Auth.Core.csproj" />
	</ItemGroup>
</Project>
