<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props" />

	<ItemGroup>
		<ProjectReference Include="..\BeniceSoft.Abp.Ddd.Application.Contracts\BeniceSoft.Abp.Ddd.Application.Contracts.csproj" />
		<ProjectReference Include="..\BeniceSoft.Abp.Ddd.Domain\BeniceSoft.Abp.Ddd.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Mapster" />
		<PackageReference Include="Volo.Abp.Ddd.Application" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BeniceSoft.Abp.Ddd.Application.Contracts\BeniceSoft.Abp.Ddd.Application.Contracts.csproj" />
		<ProjectReference Include="..\BeniceSoft.Abp.Ddd.Domain\BeniceSoft.Abp.Ddd.Domain.csproj" />
	</ItemGroup>

</Project>
