<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props" />

	<ItemGroup>
		<ProjectReference Include="..\BeniceSoft.Abp.Core\BeniceSoft.Abp.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Lock\Lua\Extend.lua" />
		<EmbeddedResource Include="Lock\Lua\Unlock.lua" />
		<PackageReference Include="StackExchange.Redis" />
		<PackageReference Include="Volo.Abp.Core" />
	</ItemGroup>

</Project>

