<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props" />

	<ItemGroup>
		<PackageReference Include="Volo.Abp.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BeniceSoft.Abp.EventBus.Dtm\BeniceSoft.Abp.EventBus.Dtm.csproj" />
	</ItemGroup>

</Project>
