<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props" />
	<ItemGroup>
	  <Content Remove="C:\Users\Administrator\.nuget\packages\volo.abp.aspnetcore\10.6.0\contentFiles\any\net10.0\Volo.Abp.AspNetCore.abppkg.analyze.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Dtmcli" />
		<PackageReference Include="Volo.Abp.AspNetCore" />
		<PackageReference Include="Volo.Abp.EventBus.RabbitMQ" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BeniceSoft.Abp.Core\BeniceSoft.Abp.Core.csproj" />
		<ProjectReference Include="..\BeniceSoft.Abp.EventBus.Dtm\BeniceSoft.Abp.EventBus.Dtm.csproj" />
		<ProjectReference Include="..\BeniceSoft.Core\BeniceSoft.Core.csproj" />
	</ItemGroup>

</Project>
