<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props" />

	<ItemGroup>
		<PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.Data.SqlClient" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BeniceSoft.Abp.EntityFrameworkCore\BeniceSoft.Abp.EntityFrameworkCore.csproj" />
	</ItemGroup>

</Project>
