<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props" />

	<ItemGroup>
		<ProjectReference Include="..\BeniceSoft.Core\BeniceSoft.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SqlKata" />

	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.Core" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Microsoft.SourceLink.GitHub" />
	</ItemGroup>

</Project>
