<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props" />

	<ItemGroup>
		<PackageReference Include="OpenIddict.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.Core" />
		<PackageReference Include="Volo.Abp.Security" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BeniceSoft.Abp.Core\BeniceSoft.Abp.Core.csproj" />
	</ItemGroup>

</Project>
